### ISSUE TITLE
Fatal error: Class 'Afosto\ApiClient\Components\Storage\FileStorage' not found

### ISSUE THREAD

**Issue by Grendel7** [afosto/api-client#1]
I'm unable to use any storage adapter in my project. My code looks as follows:

```
require_once __DIR__.'/vendor/autoload.php';

$storage = new Afosto\ApiClient\Components\Storage\FileStorage([
    'directory' => $app['base_path'] . '/tmp/'
]);

\Afosto\ApiClient\App::run($storage, $app['config']['api_token'], $app['config']['api_secret']);
```

In response, I get the following exception:

`Fatal error: Class 'Afosto\ApiClient\Components\Storage\FileStorage' not found`

I suspect this may have something to do with using PSR-4 autoloading on multiple directories at the same time, confusing the autoloader. Many libraries simply use one base directory and make the namespace tree match the directory tree, rather than using a Yii-like "we have specific directories for everything and load the contents of all of them manually".

**Comment by afosto** [comment]
Did you install with composer (this takes care of the autoloading for you).

**Comment by Grendel7** [comment]
Of course I used Composer. My Composer.json looks as follows:

```
{
  "require": {
    "silex/silex": "~1.3",
    "afosto/api-client": "~0.3"
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  }
}
```

**Comment by afosto** [comment]
Did you include the autoloader in the vendor folder? Could you post your bootstrap script?

**Comment by Grendel7** [comment]
@afosto The code shown in the initial post shows the (abbreviated) code sample.
