### ISSUE TITLE
Undefined constant PAGE_SIZE in Api/Pagination.php line 60

### ISSUE THREAD

**Issue by Grendel7** [afosto/api-client#7]
When trying to do `$model->findPage()`, the notice `Use of undefined constant PAGE_SIZE - assumed 'PAGE_SIZE' in vendor/afosto/api-client/src/Api/Pagination.php on line 60` is generated.

This issue is caused by:
- `findPage()` not passing the provided `$pageSize` parameter to the Paginator constructor because `PaginationTrait->getPagination()` doesn't support the attribute.
- The Pagination constructor defaulting to the `PAGE_SIZE` constant despite not being certain whether it has been defined.

Recommendation:
- Define a default page size constant somewhere in the client which is always set to a valid value the paginator can default to.

**Comment by afosto** [comment]
https://github.com/afosto/api-client/pull/9
